Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "dhcp_server"
    config.vm.network "private_network", ip: "192.168.130.1"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y isc-dhcp-server
      #sudo sed -i 's/INTERFACESv4=""/INTERFACESv4="eth1"/' /etc/default/isc-dhcp-server
      sudo cat > /etc/dhcp/dhcpd.conf << EOF
      subnet 192.168.130.0 netmask 255.255.255.0 {
        range 192.168.130.100 192.168.130.200;
        option routers 192.168.130.1;
              option broadcast-address 192.168.130.255;
        option domain-name-servers 8.8.8.8, 8.8.4.4;
      }
      EOF
      sudo systemctl restart isc-dhcp-server
    SHELL
  end